# 20 DECKS x 25 CARDS = 500 COMPLETE PYTHON QUESTIONS
# Alternating distribution: Deck 1: 13 FSRS, 12 SM-2; Deck 2: 12 FSRS, 13 SM-2; etc.

PYTHON_DECKS_DATA = [
    # DECK 1: Python Basics (25 cards)
    ("1. Python Basics - Introduction", [
        ("What is Python?", "A high-level, interpreted programming language created by Guido van Rossum"),
        ("Who created Python?", "Guido van Rossum"),
        ("When was Python created?", "1991"),
        ("What is PEP 8?", "Python Enhancement Proposal - Style guide for Python code"),
        ("What are the key features of Python?", "Easy to learn, interpreted, object-oriented, dynamic typing, extensive libraries"),
        ("What is the difference between Python 2 and Python 3?", "Python 2 is legacy, Python 3 is current with better Unicode support"),
        ("How do you print in Python?", "print('Hello World')"),
        ("What is the correct file extension for Python?", ".py"),
        ("What is IDLE?", "Integrated Development and Learning Environment - Python's built-in IDE"),
        ("What is the difference between interpreted and compiled languages?", "Interpreted executes line by line, compiled converts entire code"),
        ("What is dynamic typing?", "Variables don't need explicit type declaration; type is determined at runtime"),
        ("Is Python case-sensitive?", "Yes, 'Variable' and 'variable' are different"),
        ("What is the use of indentation in Python?", "Defines code blocks instead of braces {}"),
        ("How many spaces for indentation?", "4 spaces (recommended by PEP 8)"),
        ("What is the maximum line length?", "79 characters (PEP 8 recommendation)"),
        ("How to write multi-line statements?", "Use line continuation character \\ or parentheses"),
        ("What is the Zen of Python?", "Collection of 19 guiding principles for Python design"),
        ("How to see the Zen of Python?", "import this"),
        ("What is the difference between / and //?", "/ gives float result, // gives integer floor division"),
        ("What is the modulo operator?", "% - returns remainder of division"),
        ("What is exponentiation operator?", "** - raises to power"),
        ("What is operator precedence?", "Rules determining order of operations: PEMDAS"),
        ("What are comparison operators?", "==, !=, >, <, >=, <="),
        ("What are logical operators?", "and, or, not"),
        ("What is assignment operator?", "= assigns value to variable"),
    ]),
    
    # DECK 2: Variables & Data Types (25 cards)
    ("2. Variables & Data Types", [
        ("How to create a variable?", "variable_name = value"),
        ("What are the rules for variable names?", "Start with letter/_, contain letters/numbers/_, case-sensitive"),
        ("What is dynamic typing?", "Variables can change type at runtime"),
        ("What is type() function?", "Returns the data type of a variable"),
        ("What is isinstance() function?", "Checks if object is of specified type"),
        ("What are the numeric types?", "int, float, complex"),
        ("What is int?", "Integer numbers without decimal point"),
        ("What is float?", "Numbers with decimal point"),
        ("What is complex?", "Numbers with real and imaginary part (j suffix)"),
        ("What is string?", "Sequence of characters in quotes"),
        ("Single vs double quotes?", "Both work for strings, double allows single quotes inside"),
        ("What are multi-line strings?", "Triple quotes ''' or \"\"\""),
        ("What is string concatenation?", "Joining strings with + operator"),
        ("What is string repetition?", "* operator repeats string"),
        ("What is string slicing?", "Extracting substring using [start:end]"),
        ("What is negative indexing?", "Counts from end with -1 as last character"),
        ("What is len() function?", "Returns length of string"),
        ("What are string methods?", "upper(), lower(), strip(), replace(), split(), join()"),
        ("What is f-string?", "Formatted string literal: f'Hello {name}'"),
        ("What is format() method?", "String formatting: 'Hello {}'.format(name)"),
        ("What is boolean?", "True/False values"),
        ("What is None?", "Represents absence of value"),
        ("What is type conversion?", "Converting between types: int(), float(), str()"),
        ("What is implicit conversion?", "Automatic type conversion by Python"),
        ("What is explicit conversion?", "Manual type conversion using functions"),
    ]),
    
    # DECK 3: Lists (25 cards)
    ("3. Lists", [
        ("How to create a list?", "my_list = [1, 2, 3]"),
        ("Are lists ordered?", "Yes, items have defined order"),
        ("Are lists mutable?", "Yes, can change items"),
        ("Can lists have duplicates?", "Yes"),
        ("How to access list items?", "By index: my_list[0]"),
        ("What is negative indexing?", "my_list[-1] gives last item"),
        ("What is list slicing?", "my_list[1:4] gives items 1,2,3"),
        ("How to change list item?", "my_list[0] = new_value"),
        ("How to loop through list?", "for item in my_list:"),
        ("How to check if item exists?", "if item in my_list:"),
        ("What is append() method?", "Adds item to end: my_list.append(item)"),
        ("What is insert() method?", "Inserts at index: my_list.insert(pos, item)"),
        ("What is extend() method?", "Adds multiple items: my_list.extend([a,b,c])"),
        ("What is remove() method?", "Removes first occurrence: my_list.remove(item)"),
        ("What is pop() method?", "Removes and returns last/index item: my_list.pop()"),
        ("What is clear() method?", "Empties list: my_list.clear()"),
        ("What is index() method?", "Returns index of item: my_list.index(item)"),
        ("What is count() method?", "Counts occurrences: my_list.count(item)"),
        ("How to sort a list?", "my_list.sort() or sorted(my_list)"),
        ("How to reverse a list?", "my_list.reverse() or my_list[::-1]"),
        ("How to copy a list?", "my_list.copy() or my_list[:]"),
        ("What is list comprehension?", "[x*2 for x in range(5)] creates [0,2,4,6,8]"),
        ("What is nested list?", "List containing other lists"),
        ("How to flatten nested list?", "List comprehension: [item for sublist in nested for item in sublist]"),
        ("What is the difference between list and tuple?", "Lists mutable, tuples immutable"),
    ]),
    
    # DECK 4: Tuples (25 cards)
    ("4. Tuples", [
        ("How to create a tuple?", "my_tuple = (1, 2, 3)"),
        ("Are tuples ordered?", "Yes"),
        ("Are tuples mutable?", "No, immutable"),
        ("Can tuples have duplicates?", "Yes"),
        ("Single item tuple?", "my_tuple = (1,) - comma required"),
        ("How to access tuple items?", "By index: my_tuple[0]"),
        ("What is tuple unpacking?", "a, b, c = (1, 2, 3)"),
        ("What is tuple concatenation?", "tuple1 + tuple2"),
        ("What is tuple repetition?", "tuple1 * 2"),
        ("How to loop through tuple?", "for item in my_tuple:"),
        ("How to check if item exists?", "if item in my_tuple:"),
        ("What is count() method?", "Counts occurrences: my_tuple.count(item)"),
        ("What is index() method?", "Returns index of item: my_tuple.index(item)"),
        ("What is the advantage of tuple over list?", "Faster, memory efficient, immutable"),
        ("When to use tuple?", "Fixed data that shouldn't change"),
        ("Can tuple contain list?", "Yes, but list inside can be modified"),
        ("What is namedtuple?", "Tuple with named fields from collections module"),
        ("How to convert list to tuple?", "tuple(my_list)"),
        ("How to convert tuple to list?", "list(my_tuple)"),
        ("What is the difference between tuple and list?", "Mutability is main difference"),
        ("What is the difference between tuple and set?", "Tuple ordered/duplicates, set unordered/unique"),
        ("What is the difference between tuple and dictionary?", "Tuple index-based, dict key-based"),
        ("Can tuple be used as dictionary key?", "Yes, because immutable"),
        ("What is the memory difference?", "Tuples use less memory than lists"),
        ("What is the speed difference?", "Tuples are slightly faster for iteration"),
    ]),
    
    # DECK 5: Dictionaries (25 cards)
    ("5. Dictionaries", [
        ("How to create a dictionary?", "my_dict = {'key': 'value'}"),
        ("Are dictionaries ordered?", "Yes (Python 3.7+ maintains insertion order)"),
        ("Are dictionaries mutable?", "Yes"),
        ("Can dictionaries have duplicate keys?", "No, later overwrites earlier"),
        ("What can be dictionary keys?", "Immutable types: strings, numbers, tuples"),
        ("What can be dictionary values?", "Any type"),
        ("How to access value?", "my_dict['key'] or my_dict.get('key')"),
        ("What is get() method?", "Returns value or default if key not found"),
        ("How to add/update item?", "my_dict['new_key'] = 'value'"),
        ("How to remove item?", "del my_dict['key'] or my_dict.pop('key')"),
        ("What is popitem()?", "Removes and returns last inserted item"),
        ("What is clear() method?", "Empties dictionary"),
        ("How to loop through keys?", "for key in my_dict:"),
        ("How to loop through values?", "for value in my_dict.values():"),
        ("How to loop through items?", "for key, value in my_dict.items():"),
        ("How to check if key exists?", "if key in my_dict:"),
        ("What is len()?", "Returns number of items"),
        ("What is copy()?", "Returns shallow copy"),
        ("What is fromkeys()?", "Creates dictionary from keys"),
        ("What is setdefault()?", "Returns value, inserts if key missing"),
        ("What is update()?", "Updates with another dictionary"),
        ("What is dictionary comprehension?", "{x: x**2 for x in range(5)}"),
        ("What is defaultdict?", "Dict with default value from collections"),
        ("What is OrderedDict?", "Dict that remembers order (deprecated in Python 3.7+)"),
        ("What is the difference between dict and list?", "Dict key-based, list index-based"),
    ]),
    
    # DECK 6: Sets (25 cards)
    ("6. Sets", [
        ("How to create a set?", "my_set = {1, 2, 3}"),
        ("How to create empty set?", "my_set = set() (not {} which is dict)"),
        ("Are sets ordered?", "No, unordered"),
        ("Are sets mutable?", "Yes, but elements must be immutable"),
        ("Can sets have duplicates?", "No, all elements unique"),
        ("How to add item?", "my_set.add(element)"),
        ("How to remove item?", "my_set.remove(element) raises error if missing"),
        ("What is discard()?", "Removes item, no error if missing"),
        ("What is pop() on set?", "Removes and returns arbitrary item"),
        ("What is clear()?", "Empties set"),
        ("What is union?", "set1 | set2 or set1.union(set2)"),
        ("What is intersection?", "set1 & set2 or set1.intersection(set2)"),
        ("What is difference?", "set1 - set2 or set1.difference(set2)"),
        ("What is symmetric difference?", "set1 ^ set2 or set1.symmetric_difference(set2)"),
        ("What is subset?", "set1.issubset(set2) or set1 <= set2"),
        ("What is superset?", "set1.issuperset(set2) or set1 >= set2"),
        ("What is disjoint?", "No common elements: set1.isdisjoint(set2)"),
        ("How to loop through set?", "for item in my_set:"),
        ("What is frozenset?", "Immutable version of set"),
        ("What is set comprehension?", "{x for x in range(5)}"),
        ("What is the difference between set and list?", "Set unique/unordered, list ordered/duplicates"),
        ("What is the difference between set and tuple?", "Set mutable/unique, tuple immutable/ordered"),
        ("When to use set?", "Membership testing, removing duplicates, set operations"),
        ("What is the time complexity of 'in'?", "O(1) for set, O(n) for list"),
        ("Can set contain list?", "No, lists are unhashable"),
    ]),
    
    # DECK 7: Conditional Statements (25 cards)
    ("7. Conditional Statements", [
        ("What is if statement?", "if condition: executes code block if True"),
        ("What is elif?", "else-if: checks additional conditions"),
        ("What is else?", "Executes if all conditions False"),
        ("What is indentation in conditionals?", "Code block must be indented"),
        ("What is nested if?", "if inside another if"),
        ("What is ternary operator?", "x if condition else y"),
        ("What is short-circuit evaluation?", "and stops at first False, or stops at first True"),
        ("What is truthy/falsy?", "Values that evaluate to True/False in boolean context"),
        ("What are falsy values?", "None, False, 0, empty sequences, empty mappings"),
        ("What is truthy value?", "All values not falsy"),
        ("What is pass statement?", "Placeholder that does nothing"),
        ("What is match-case?", "Structural pattern matching (Python 3.10+)"),
        ("What is a switch-case alternative?", "if-elif-else chain or dictionary mapping"),
        ("How to check multiple conditions?", "Using and/or operators"),
        ("What is the difference between = and ==", "= assignment, == comparison"),
        ("What is the difference between is and ==", "is checks identity, == checks value"),
        ("What is chained comparison?", "a < b < c is valid in Python"),
        ("What is the difference between if and elif?", "if checks always, elif checks only if previous False"),
        ("Can else be used without if?", "No"),
        ("How many elif can you have?", "Unlimited"),
        ("What is conditional expression?", "Another name for ternary operator"),
        ("What is the walrus operator?", ":= assigns and returns value (Python 3.8+)"),
        ("What is the difference between if and while?", "if executes once, while repeats until condition False"),
        ("How to write if on one line?", "Can be written but not recommended for complex conditions"),
        ("What is the common pattern for multiple conditions?", "if-elif-else chain"),
    ]),
    
    # DECK 8: Loops (25 cards)
    ("8. Loops", [
        ("What is for loop?", "Iterates over sequence"),
        ("What is while loop?", "Repeats while condition is True"),
        ("What is range() function?", "Generates sequence of numbers"),
        ("What are the parameters of range()?", "range(stop), range(start, stop), range(start, stop, step)"),
        ("How to loop through list?", "for item in my_list:"),
        ("How to get index in loop?", "for i, item in enumerate(my_list):"),
        ("What is nested loop?", "Loop inside another loop"),
        ("What is break statement?", "Exits loop immediately"),
        ("What is continue statement?", "Skips to next iteration"),
        ("What is pass statement?", "Placeholder, does nothing"),
        ("What is else in loop?", "Executes if loop completes without break"),
        ("What is infinite loop?", "Loop that never ends, use Ctrl+C to stop"),
        ("How to avoid infinite loop?", "Ensure condition becomes False or use break"),
        ("What is loop optimization?", "Minimize operations inside loop, use list comprehensions"),
        ("What is the difference between for and while?", "for for known iterations, while for unknown"),
        ("What is the difference between break and continue?", "break exits loop, continue skips iteration"),
        ("How to loop backwards?", "for i in range(len(list)-1, -1, -1)"),
        ("What is enumerate()?", "Returns index and value"),
        ("What is zip()?", "Iterates over multiple sequences in parallel"),
        ("What is reversed()?", "Returns iterator in reverse order"),
        ("What is sorted()?", "Returns sorted list"),
        ("What is the difference between for and list comprehension?", "List comprehension creates list, for loop executes code"),
        ("How to loop through dictionary?", "for key, value in dict.items():"),
        ("What is while-else?", "Else executes if while completes without break"),
        ("What is the performance difference?", "List comprehensions are faster than for loops"),
    ]),
    
    # DECK 9: Functions (25 cards)
    ("9. Functions", [
        ("How to define function?", "def function_name():"),
        ("What is function call?", "function_name()"),
        ("What are parameters?", "Variables in function definition"),
        ("What are arguments?", "Values passed to function"),
        ("What is positional argument?", "Arguments in order"),
        ("What is keyword argument?", "name=value format"),
        ("What is default parameter?", "Parameter with default value: def func(x=5)"),
        ("What is return statement?", "Returns value to caller"),
        ("What is None return?", "Functions without return return None"),
        ("What is docstring?", "String to document function"),
        ("What is scope?", "Region where variable exists"),
        ("What is local variable?", "Variable inside function"),
        ("What is global variable?", "Variable outside functions"),
        ("What is global keyword?", "Modifies global variable inside function"),
        ("What is nonlocal keyword?", "Modifies variable in outer (but not global) scope"),
        ("What is recursion?", "Function calling itself"),
        ("What is base case?", "Condition that stops recursion"),
        ("What is stack overflow?", "Too many recursive calls"),
        ("What is lambda function?", "Anonymous function: lambda x: x*2"),
        ("What is map() function?", "Applies function to all items"),
        ("What is filter() function?", "Filters items based on function"),
        ("What is reduce() function?", "Applies rolling computation"),
        ("What is function composition?", "Combining functions"),
        ("What is higher-order function?", "Function that takes/returns function"),
        ("What is the difference between function and method?", "Method belongs to object/class"),
    ]),
    
    # DECK 10: Classes & OOP (25 cards)
    ("10. Classes & Object Oriented Programming", [
        ("How to create class?", "class MyClass:"),
        ("How to create object?", "my_obj = MyClass()"),
        ("What is __init__ method?", "Constructor called on object creation"),
        ("What is self parameter?", "Reference to current instance"),
        ("What is instance variable?", "Unique to each instance"),
        ("What is class variable?", "Shared across all instances"),
        ("What is method?", "Function defined inside class"),
        ("What is instance method?", "Method with self parameter"),
        ("What is class method?", "Method with @classmethod decorator"),
        ("What is static method?", "Method with @staticmethod decorator"),
        ("What is inheritance?", "Class inherits from parent"),
        ("What is single inheritance?", "Inherits from one parent"),
        ("What is multiple inheritance?", "Inherits from multiple parents"),
        ("What is multilevel inheritance?", "Child becomes parent for another"),
        ("What is method overriding?", "Child redefines parent method"),
        ("What is super()?", "Calls parent method"),
        ("What is polymorphism?", "Same method name, different behavior"),
        ("What is encapsulation?", "Hiding internal data"),
        ("What is private attribute?", "Prefix __ (double underscore)"),
        ("What is name mangling?", "_ClassName__attribute for private"),
        ("What is property decorator?", "@property makes method accessible as attribute"),
        ("What is setter?", "@attr.setter allows property assignment"),
        ("What is abstraction?", "Hiding implementation details"),
        ("What is composition?", "Class containing instances of other classes"),
        ("What is the difference between class and instance?", "Class is blueprint, instance is object"),
    ]),
    
    # DECK 11: Exception Handling (25 cards)
    ("11. Exception Handling", [
        ("What is exception?", "Error that occurs during execution"),
        ("What is try block?", "Code that might raise exception"),
        ("What is except block?", "Handles specific exception"),
        ("What is else in try-except?", "Executes if no exception"),
        ("What is finally block?", "Always executes, for cleanup"),
        ("What is raising exception?", "raise Exception('message')"),
        ("What are built-in exceptions?", "ValueError, TypeError, ZeroDivisionError, etc"),
        ("What is custom exception?", "Create class inheriting Exception"),
        ("What is assertion?", "assert condition, message"),
        ("What is Exception hierarchy?", "BaseException -> Exception -> Specific exceptions"),
        ("What is try-except-else-finally order?", "try -> except -> else -> finally"),
        ("What is multiple except?", "Handle different exceptions differently"),
        ("What is bare except?", "except: catches all exceptions (not recommended)"),
        ("What is logging exceptions?", "Use logging module"),
        ("What is traceback?", "Stack trace of exception"),
        ("What is sys.exc_info()?", "Returns exception info"),
        ("What is context manager for exceptions?", "with statement handles exceptions"),
        ("What is the difference between except and except Exception as e?", "except catches all, except Exception catches non-system-exiting"),
        ("What is KeyboardInterrupt?", "Exception from Ctrl+C"),
        ("What is SystemExit?", "Exception from sys.exit()"),
        ("What is MemoryError?", "Out of memory"),
        ("What is RecursionError?", "Maximum recursion depth exceeded"),
        ("What is NameError?", "Variable not defined"),
        ("What is KeyError?", "Dictionary key not found"),
        ("What is IndexError?", "List index out of range"),
    ]),
    
    # DECK 12: File Handling (25 cards)
    ("12. File Handling", [
        ("How to open file?", "open('filename', 'mode')"),
        ("What is with statement?", "Automatically closes file: with open() as f:"),
        ("What are file modes?", "r-read, w-write, a-append, x-create, b-binary"),
        ("What is read() method?", "Reads entire file"),
        ("What is readline()?", "Reads one line"),
        ("What is readlines()?", "Reads all lines into list"),
        ("What is write() method?", "Writes string to file"),
        ("What is writelines()?", "Writes list of strings"),
        ("What is close() method?", "Closes file"),
        ("What is seek() method?", "Moves file pointer"),
        ("What is tell() method?", "Returns current position"),
        ("What is file object?", "Object returned by open()"),
        ("What is binary mode?", "'rb' or 'wb' for non-text files"),
        ("What is JSON?", "JavaScript Object Notation"),
        ("How to parse JSON?", "json.load() for file, json.loads() for string"),
        ("How to write JSON?", "json.dump() to file, json.dumps() to string"),
        ("What is CSV?", "Comma Separated Values"),
        ("What is csv module?", "Reading/writing CSV files"),
        ("What is csv.reader?", "Reads CSV rows"),
        ("What is csv.writer?", "Writes CSV rows"),
        ("What is pickle module?", "Serializes Python objects"),
        ("What is shelve module?", "Persistent dictionary"),
        ("What is pathlib?", "Object-oriented paths"),
        ("What is os.path?", "Path manipulation functions"),
        ("What is shutil?", "High-level file operations"),
    ]),
    
    # DECK 13: Modules & Packages (25 cards)
    ("13. Modules & Packages", [
        ("What is module?", "Python file with code"),
        ("How to import module?", "import module_name"),
        ("What is from import?", "from module import function"),
        ("What is as alias?", "import module as alias"),
        ("What is __name__?", "Module name or '__main__' if run directly"),
        ("What is if __name__ == '__main__'?", "Code runs only when script executed directly"),
        ("What is package?", "Directory with __init__.py"),
        ("What is __init__.py?", "Marks directory as package"),
        ("What is relative import?", "from . import module"),
        ("What is absolute import?", "from package import module"),
        ("What is sys.path?", "List of module search paths"),
        ("What is PYTHONPATH?", "Environment variable for module search"),
        ("What is built-in module?", "Standard library module"),
        ("What is dir() function?", "Lists attributes of module"),
        ("What is help() function?", "Shows documentation"),
        ("What is __all__?", "List of public names in module"),
        ("What is namespace?", "Container of names"),
        ("What is scope resolution?", "LEGB rule: Local, Enclosing, Global, Built-in"),
        ("How to reload module?", "importlib.reload(module)"),
        ("What is __file__?", "Path to module file"),
        ("What is __doc__?", "Module docstring"),
        ("What is __package__?", "Package name"),
        ("What is __path__?", "Package search path"),
        ("What is namespace package?", "Package spanning multiple directories"),
        ("What is zipimporter?", "Import from zip files"),
    ]),
    
    # DECK 14: Date & Time (25 cards)
    ("14. Date & Time", [
        ("What is datetime module?", "Date and time manipulation"),
        ("What is datetime class?", "Combines date and time"),
        ("What is date class?", "Year, month, day"),
        ("What is time class?", "Hour, minute, second, microsecond"),
        ("How to get current date?", "datetime.date.today()"),
        ("How to get current datetime?", "datetime.datetime.now()"),
        ("What is timedelta?", "Difference between dates/times"),
        ("What is strftime()?", "Format datetime to string"),
        ("What is strptime()?", "Parse string to datetime"),
        ("What is time module?", "Time-related functions"),
        ("What is time.time()?", "Seconds since epoch"),
        ("What is time.sleep()?", "Pause execution"),
        ("What is calendar module?", "Calendar-related functions"),
        ("What is ISO format?", "YYYY-MM-DD HH:MM:SS"),
        ("What is UTC?", "Coordinated Universal Time"),
        ("What is timezone?", "Geographic region with uniform time"),
        ("What is pytz module?", "Third-party timezone library"),
        ("What is dateutil module?", "Powerful date parsing"),
        ("How to compare dates?", "Use comparison operators"),
        ("How to add days to date?", "date + timedelta(days=n)"),
        ("What is weekday()?", "Returns day of week (0=Monday)"),
        ("What is isoweekday()?", "Returns day of week (1=Monday)"),
        ("What is ISO calendar?", "ISO year, week, weekday"),
        ("How to get Unix timestamp?", "datetime.timestamp()"),
        ("How to convert timestamp to datetime?", "datetime.fromtimestamp()"),
    ]),
    
    # DECK 15: Regular Expressions (25 cards)
    ("15. Regular Expressions", [
        ("What is regex?", "Pattern matching in text"),
        ("What is re module?", "Regular expression module"),
        ("What is re.search()?", "Searches for pattern anywhere"),
        ("What is re.match()?", "Matches pattern at start"),
        ("What is re.findall()?", "Returns all matches"),
        ("What is re.finditer()?", "Returns iterator of matches"),
        ("What is re.sub()?", "Substitutes matches"),
        ("What is re.split()?", "Splits string by pattern"),
        ("What is re.compile()?", "Compiles pattern for reuse"),
        ("What is raw string?", "r'pattern' - backslashes literal"),
        ("What is . (dot) in regex?", "Matches any character except newline"),
        ("What is ^ in regex?", "Matches start of string"),
        ("What is $ in regex?", "Matches end of string"),
        ("What is * in regex?", "Matches 0 or more repetitions"),
        ("What is + in regex?", "Matches 1 or more repetitions"),
        ("What is ? in regex?", "Matches 0 or 1 repetition"),
        ("What is {n} in regex?", "Matches exactly n repetitions"),
        ("What is {n,} in regex?", "Matches n or more repetitions"),
        ("What is {n,m} in regex?", "Matches between n and m repetitions"),
        ("What is [] in regex?", "Character class"),
        ("What is | in regex?", "Alternation (OR)"),
        ("What is () in regex?", "Grouping and capturing"),
        (r"What is \d in regex?", "Digit [0-9]"),
        (r"What is \w in regex?", "Word character [a-zA-Z0-9_]"),
        (r"What is \s in regex?", "Whitespace"),
    ]),
    
    # DECK 16: Advanced Functions & Decorators (25 cards)
    ("16. Advanced Functions & Decorators", [
        ("What is a decorator?", "Function that modifies another function's behavior"),
        ("How to create a decorator?", "def decorator(func):\n    def wrapper():\n        print('Before')\n        func()\n        print('After')\n    return wrapper"),
        ("What is @ syntax for decorators?", "@decorator_name above function definition"),
        ("What is functools.wraps?", "Preserves original function metadata"),
        ("What is a class decorator?", "Class that takes a function and returns a callable"),
        ("What is a generator?", "Function that yields values using yield keyword"),
        ("What is yield vs return?", "yield produces a generator, return stops function"),
        ("What is next() on generator?", "Gets next value from generator"),
        ("What is generator expression?", "(x*2 for x in range(5)) - like list comprehension but lazy"),
        ("What is iterable vs iterator?", "Iterable has __iter__(), iterator has __next__()"),
        ("What is the difference between generator and list?", "Generator doesn't store all values in memory"),
        ("What is closure?", "Function that remembers variables from outer scope"),
        ("What is partial function?", "functools.partial fixes some arguments"),
        ("What is singledispatch?", "Function overloading based on first argument type"),
        ("What is lru_cache?", "Decorator for memoization/caching"),
        ("What is total_ordering?", "Class decorator to fill in missing comparison methods"),
        ("What is contextlib?", "Utilities for context managers"),
        ("What is contextmanager decorator?", "Turns generator into context manager"),
        ("What is ExitStack?", "Combines multiple context managers"),
        ("What is suppress?", "Context manager to ignore specified exceptions"),
        ("What is redirect_stdout?", "Redirects standard output"),
        ("What is nullcontext?", "Context manager that does nothing"),
        ("What is cached_property?", "Property that caches its result"),
        ("What is typing.Callable?", "Type hint for callable objects"),
        ("What is functools.reduce?", "Applies rolling computation"),
    ]),
    
    # DECK 17: Advanced Data Structures (25 cards)
    ("17. Advanced Data Structures", [
        ("What is collections.Counter?", "Dict subclass for counting hashable objects"),
        ("What is collections.defaultdict?", "Dict with default factory for missing keys"),
        ("What is collections.OrderedDict?", "Dict that remembers insertion order"),
        ("What is collections.deque?", "Double-ended queue for fast appends/pops"),
        ("What is collections.ChainMap?", "Groups multiple dicts into single view"),
        ("What is collections.namedtuple?", "Tuple with named fields"),
        ("What is collections.UserDict?", "Wrapper for easier dict subclassing"),
        ("What is collections.UserList?", "Wrapper for easier list subclassing"),
        ("What is heapq?", "Heap queue algorithm (priority queue)"),
        ("What is bisect?", "Binary search and insertion"),
        ("What is array module?", "Efficient array of numeric values"),
        ("What is weakref?", "References that don't prevent garbage collection"),
        ("What is enum module?", "Defines enumerated constants"),
        ("What is dataclasses?", "Class decorator for data containers"),
        ("What is @dataclass?", "Generates __init__, __repr__, __eq__ automatically"),
        ("What is field() in dataclass?", "Customizes field behavior"),
        ("What is typing.NamedTuple?", "Named tuple with type hints"),
        ("What is typing.TypedDict?", "Dict with specific key-value types"),
        ("What is queue module?", "Thread-safe queues: Queue, LifoQueue, PriorityQueue"),
        ("What is multiprocessing.Queue?", "Queue for inter-process communication"),
        ("What is struct module?", "Packs/unpacks binary data"),
        ("What is memoryview?", "Access memory without copying"),
        ("What is bytearray?", "Mutable sequence of bytes"),
        ("What is frozenset?", "Immutable version of set"),
        ("What is itertools module?", "Functions for efficient looping"),
    ]),
    
    # DECK 18: Itertools & Functional Programming (25 cards)
    ("18. Itertools & Functional Programming", [
        ("What is itertools.chain()?", "Chains multiple iterables"),
        ("What is itertools.cycle()?", "Cycles through iterable infinitely"),
        ("What is itertools.repeat()?", "Repeats object infinitely"),
        ("What is itertools.count()?", "Counts from start infinitely"),
        ("What is itertools.accumulate()?", "Running accumulation"),
        ("What is itertools.product()?", "Cartesian product"),
        ("What is itertools.permutations()?", "All possible orderings"),
        ("What is itertools.combinations()?", "All combinations without repetition"),
        ("What is itertools.combinations_with_replacement()?", "Combinations with repetition"),
        ("What is itertools.groupby()?", "Groups consecutive items by key"),
        ("What is itertools.islice()?", "Slices iterator"),
        ("What is itertools.compress()?", "Filters using selector"),
        ("What is itertools.dropwhile()?", "Drops items while condition true"),
        ("What is itertools.takewhile()?", "Takes items while condition true"),
        ("What is itertools.filterfalse()?", "Filters opposite of filter()"),
        ("What is itertools.zip_longest()?", "Zips with fillvalue"),
        ("What is itertools.starmap()?", "Map with unpacked arguments"),
        ("What is itertools.tee()?", "Creates multiple independent iterators"),
        ("What is functools.partial?", "Partial function application"),
        ("What is operator module?", "Function equivalents of operators"),
        ("What is operator.itemgetter()?", "Gets item from object"),
        ("What is operator.attrgetter()?", "Gets attribute from object"),
        ("What is operator.methodcaller()?", "Calls method on object"),
        ("What is more-itertools?", "Third-party extended itertools library"),
        ("What is functools.reduce?", "Rolling computation"),
    ]),
    
    # DECK 19: Concurrency & Parallelism (25 cards)
    ("19. Concurrency & Parallelism", [
        ("What is threading?", "Multiple threads in same process"),
        ("What is threading.Thread?", "Class for creating threads"),
        ("What is threading.Lock?", "Mutual exclusion lock"),
        ("What is threading.RLock?", "Reentrant lock"),
        ("What is threading.Semaphore?", "Limits concurrent access"),
        ("What is threading.Event?", "Simple thread communication"),
        ("What is threading.Condition?", "Advanced thread synchronization"),
        ("What is ThreadPoolExecutor?", "Manages thread pool"),
        ("What is GIL?", "Global Interpreter Lock - limits true parallelism"),
        ("What is multiprocessing?", "Multiple processes for true parallelism"),
        ("What is multiprocessing.Process?", "Process class"),
        ("What is multiprocessing.Pool?", "Process pool"),
        ("What is multiprocessing.Queue?", "Inter-process queue"),
        ("What is multiprocessing.Value?", "Shared memory value"),
        ("What is multiprocessing.Array?", "Shared memory array"),
        ("What is multiprocessing.Manager?", "Shared objects across processes"),
        ("What is ProcessPoolExecutor?", "Manages process pool"),
        ("What is asyncio?", "Asynchronous I/O framework"),
        ("What is async def?", "Defines coroutine function"),
        ("What is await?", "Waits for coroutine result"),
        ("What is asyncio.run()?", "Runs async main function"),
        ("What is asyncio.create_task()?", "Creates task from coroutine"),
        ("What is asyncio.gather()?", "Runs multiple coroutines concurrently"),
        ("What is asyncio.sleep()?", "Non-blocking sleep"),
        ("What is the difference between threading and asyncio?", "Threading for CPU-bound, asyncio for I/O-bound"),
    ]),
    
    # DECK 20: Advanced Topics & Best Practices (25 cards)
    ("20. Advanced Topics & Best Practices", [
        ("What is type hinting?", "Annotations for variable types: def func(x: int) -> str:"),
        ("What is typing module?", "Provides type hint utilities: List, Dict, Optional, Union"),
        ("What is mypy?", "Static type checker for Python"),
        ("What is black?", "Code formatter"),
        ("What is flake8?", "Linter"),
        ("What is pylint?", "Code analysis tool"),
        ("What is pytest?", "Testing framework"),
        ("What is unittest?", "Built-in testing module"),
        ("What is mocking?", "Replacing real objects with test doubles"),
        ("What is profiling?", "Measuring code performance"),
        ("What is cProfile?", "Built-in profiler"),
        ("What is logging?", "Logging framework"),
        ("What are logging levels?", "DEBUG, INFO, WARNING, ERROR, CRITICAL"),
        ("What is __slots__?", "Reduces memory usage by preventing __dict__"),
        ("What is metaclass?", "Class of a class (type is default metaclass)"),
        ("What is __new__?", "Called before __init__ to create instance"),
        ("What is __call__?", "Makes instance callable"),
        ("What is __getattr__ vs __getattribute__?", "__getattr__ called only if attribute missing, __getattribute__ always called"),
        ("What is descriptor protocol?", "__get__, __set__, __delete__"),
        ("What is property?", "Descriptor for getter/setter"),
        ("What is __enter__ and __exit__?", "Context manager protocol"),
        ("What is __aenter__ and __aexit__?", "Async context manager protocol"),
        ("What is __await__?", "Makes object awaitable"),
        ("What is __iter__ and __next__?", "Iterator protocol"),
        ("What is WSGI?", "Web Server Gateway Interface - standard for Python web apps"),
    ]),
]

for i in range(4, 21):
    PYTHON_DECKS_DATA.append((f"{i}. Python Topic {i}", [
        (f"Python Question {j+1} for Topic {i}", f"Python Answer {j+1} for Topic {i}") for j in range(25)
    ]))

def create_full_python_course(user_id, db, Deck, Card):
    """Create all 20 decks with 500 Python questions - Alternating FSRS/SM-2 per deck"""
    decks_created = 0
    cards_created = 0
    fsrs_count = 0
    sm2_count = 0
    
    for deck_index, (deck_name, cards) in enumerate(PYTHON_DECKS_DATA[:20]):
        deck = Deck(name=deck_name, user_id=user_id)
        db.session.add(deck)
        db.session.commit()
        decks_created += 1
        
        # Alternate algorithm distribution per deck
        # Deck 1: 13 FSRS, 12 SM-2
        # Deck 2: 12 FSRS, 13 SM-2
        # Deck 3: 13 FSRS, 12 SM-2
        # Deck 4: 12 FSRS, 13 SM-2 and so on...
        
        for i, (q, a) in enumerate(cards[:25]):
            # Determine algorithm based on deck index and card position
            if deck_index % 2 == 0:  # Even decks (0,2,4...): 13 FSRS first, then 12 SM-2
                if i < 13:  # First 13 cards = FSRS
                    algorithm = 'FSRS'
                    fsrs_count += 1
                else:  # Remaining 12 cards = SM-2
                    algorithm = 'SM2'
                    sm2_count += 1
            else:  # Odd decks (1,3,5...): 12 FSRS first, then 13 SM-2
                if i < 12:  # First 12 cards = FSRS
                    algorithm = 'FSRS'
                    fsrs_count += 1
                else:  # Remaining 13 cards = SM-2
                    algorithm = 'SM2'
                    sm2_count += 1
            
            card = Card(question=q, answer=a, deck_id=deck.id, algorithm=algorithm, is_mastered=False)
            db.session.add(card)
            cards_created += 1
        db.session.commit()
    
    print(f"✅ Created {decks_created} decks with {cards_created} cards")
    print(f"   📊 FSRS: {fsrs_count} cards")
    print(f"   📊 SM-2: {sm2_count} cards")
    print(f"   📊 Distribution: Alternating per deck (13/12 pattern)")
    return cards_created